name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019, ubuntu-20.04, ubuntu-22.04]
        node-version: ["12", "14", "16"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Install
        run: npm install

      - name: NPM Build
        run: npm run build --if-present

      - name: NPM Test
        run: npm run test --if-present
        env:
          BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
          BW_USERNAME: ${{ secrets.BW_USERNAME }}
          BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
